# Generated by Django 5.2b1 on 2025-03-14 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0005_rename_description_comment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('author', 'project', 'title'), name='unique_issue'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_project'),
        ),
    ]
