# Generated by Django 5.2b1 on 2025-03-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0006_issue_unique_issue_project_unique_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assigned_to',
            new_name='assigned_to',
        ),
    ]
