# Generated by Django 5.2b1 on 2025-03-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_alter_contributor_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='content',
        ),
    ]
